// <auto-generated />
using System;
using CommunityWebsite.Respositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CommunityWebsite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20191126215553_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CommunityWebsite.Models.Message", b =>
                {
                    b.Property<int>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MessageContent");

                    b.Property<string>("MessageTitle");

                    b.Property<string>("Topic");

                    b.Property<int>("UnixTimeStamp");

                    b.Property<int?>("UserID");

                    b.Property<string>("UserNameSignature");

                    b.HasKey("MessageID");

                    b.HasIndex("UserID");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("CommunityWebsite.Models.Reply", b =>
                {
                    b.Property<int>("ReplyID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MessageID");

                    b.Property<string>("ReplyContent");

                    b.Property<int>("UnixTimeStamp");

                    b.Property<int?>("UserID");

                    b.Property<string>("UserNameSignature");

                    b.HasKey("ReplyID");

                    b.HasIndex("MessageID");

                    b.HasIndex("UserID");

                    b.ToTable("Replies");
                });

            modelBuilder.Entity("CommunityWebsite.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CommunityWebsite.Models.Message", b =>
                {
                    b.HasOne("CommunityWebsite.Models.User")
                        .WithMany("GetMessageList")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("CommunityWebsite.Models.Reply", b =>
                {
                    b.HasOne("CommunityWebsite.Models.Message")
                        .WithMany("GetReplyHistory")
                        .HasForeignKey("MessageID");

                    b.HasOne("CommunityWebsite.Models.User")
                        .WithMany("GetReplyHistory")
                        .HasForeignKey("UserID");
                });
#pragma warning restore 612, 618
        }
    }
}
